# Generated by Django 5.2.17 on 2026-08-28 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('unidad_medida', models.CharField(max_length=40)),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='ingrediente_stock_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('preparacion', models.TextField()),
                ('tiempo_preparacion', models.PositiveIntegerField(help_text='Minutos')),
                ('dificultad', models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Media'), ('DIFICIL', 'Difícil')], max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('PUBLICADA', 'Publicada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='recetas', to='api.categoria')),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('estado_anterior', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('PUBLICADA', 'Publicada'), ('ARCHIVADA', 'Archivada')], max_length=10)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('PUBLICADA', 'Publicada'), ('ARCHIVADA', 'Archivada')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_recetas', to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='api.receta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='api.receta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_ingrediente', to='api.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_receta', to='api.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='api.receta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_preparacion__gt', 0)), name='receta_tiempo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'receta'), name='favorito_usuario_receta_unico'),
        ),
        migrations.AddConstraint(
            model_name='recetaingrediente',
            constraint=models.UniqueConstraint(fields=('receta', 'ingrediente'), name='receta_ingrediente_unico'),
        ),
        migrations.AddConstraint(
            model_name='recetaingrediente',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_ingrediente_positiva'),
        ),
        migrations.AddConstraint(
            model_name='valoracion',
            constraint=models.UniqueConstraint(fields=('usuario', 'receta'), name='valoracion_usuario_receta_unica'),
        ),
        migrations.AddConstraint(
            model_name='valoracion',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), name='puntuacion_valida'),
        ),
    ]
