# Generated by Django 5.2.17 on 2026-09-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_coccion',
            field=models.PositiveIntegerField(default=0, help_text='Minutos'),
        ),
    ]
