# Generated by Django 5.2.17 on 2026-09-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receta_imagen_receta_tiempo_coccion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='receta',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historialreceta',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='historialreceta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recetaingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cocinero',
        ),
        migrations.RemoveField(
            model_name='recetaingrediente',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
        migrations.DeleteModel(
            name='HistorialReceta',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='RecetaIngrediente',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
            ],
        ),
    ]
